import { StyleSheet } from 'react-native';

export const gameOverStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  scrollContent: {
    alignItems: 'center',
    padding: 20,
    paddingBottom: 40,
  },
  title: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#FFD700',
    textShadowColor: '#B8860B',
    textShadowOffset: { width: 4, height: 4 },
    textShadowRadius: 0,
    marginTop: 20,
    marginBottom: 20,
    fontFamily: 'monospace',
  },
  winnerContainer: {
    alignItems: 'center',
    marginBottom: 20,
    padding: 20,
    borderWidth: 4,
    borderColor: '#FFD700',
    backgroundColor: '#1a1a1a',
  },
  winnerLabel: {
    fontSize: 24,
    color: '#00FF00',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    marginBottom: 15,
    textShadowColor: '#00AA00',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
  },
  winnerName: {
    fontSize: 28,
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    marginTop: 15,
  },
  finalScoreContainer: {
    alignItems: 'center',
    marginVertical: 20,
    padding: 15,
    backgroundColor: '#1a1a1a',
    borderWidth: 2,
    borderColor: '#00FFFF',
    width: '100%',
  },
  finalScoreLabel: {
    fontSize: 18,
    color: '#00FFFF',
    fontFamily: 'monospace',
    marginBottom: 10,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 15,
  },
  teamScoreName: {
    fontSize: 14,
    color: '#FFFFFF',
    fontFamily: 'monospace',
    width: 80,
    textAlign: 'center',
  },
  finalScore: {
    fontSize: 40,
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'monospace',
    textShadowColor: '#FFD700',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 0,
  },
  top5Container: {
    width: '100%',
    backgroundColor: '#1a1a1a',
    padding: 15,
    borderWidth: 2,
    borderColor: '#FF00FF',
    marginVertical: 20,
  },
  top5Title: {
    fontSize: 20,
    color: '#FF00FF',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    textAlign: 'center',
    marginBottom: 15,
    textShadowColor: '#AA00AA',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
  },
  top5Row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  top5Position: {
    fontSize: 18,
    color: '#FFD700',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    width: 30,
  },
  top5PlayerInfo: {
    flex: 1,
    flexDirection: 'column',
  },
  top5PlayerName: {
    fontSize: 14,
    color: '#00FFFF',
    fontFamily: 'monospace',
  },
  top5TeamName: {
    fontSize: 11,
    color: '#888888',
    fontFamily: 'monospace',
  },
  top5Points: {
    fontSize: 16,
    color: '#00FF00',
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  newGameButton: {
    backgroundColor: '#00FF00',
    paddingHorizontal: 40,
    paddingVertical: 18,
    borderWidth: 4,
    borderColor: '#00AA00',
    marginTop: 10,
  },
  newGameButtonText: {
    fontSize: 20,
    color: '#000000',
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  footer: {
    fontSize: 16,
    color: '#666666',
    marginTop: 30,
    fontFamily: 'monospace',
  },
});
