import { StyleSheet } from 'react-native';

export const matchScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  scrollContent: {
    alignItems: 'center',
    padding: 20,
    paddingBottom: 40,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#00FF00',
    textShadowColor: '#00AA00',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 0,
    marginTop: 20,
    marginBottom: 10,
    fontFamily: 'monospace',
  },
  matchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-start',
    width: '100%',
    marginTop: 20,
    gap: 10,
  },
  matchTeam: {
    alignItems: 'center',
    flex: 1,
  },
  matchTeamName: {
    fontSize: 20,
    color: '#FFFFFF',
    fontWeight: 'bold',
    marginTop: 15,
    marginBottom: 10,
    fontFamily: 'monospace',
  },
  matchPlayersContainer: {
    backgroundColor: '#1a1a1a',
    padding: 10,
    borderWidth: 2,
    borderColor: '#FFD700',
    width: '100%',
  },
  matchPlayerName: {
    fontSize: 13,
    color: '#00FFFF',
    fontFamily: 'monospace',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  vsContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  vsText: {
    fontSize: 40,
    fontWeight: 'bold',
    color: '#FF0000',
    textShadowColor: '#AA0000',
    textShadowOffset: { width: 4, height: 4 },
    textShadowRadius: 0,
    fontFamily: 'monospace',
  },
  backButton: {
    backgroundColor: '#0000FF',
    paddingHorizontal: 30,
    paddingVertical: 15,
    marginTop: 30,
    borderWidth: 4,
    borderColor: '#0000AA',
  },
  backButtonText: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  scoreContainer: {
    marginTop: 20,
    alignItems: 'center',
  },
  scoreText: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textShadowColor: '#FFD700',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
    fontFamily: 'monospace',
  },
  matchFooter: {
    fontSize: 20,
    color: '#FF00FF',
    marginTop: 20,
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  playerRow: {
    flexDirection: 'column',
    alignItems: 'center',
    marginVertical: 6,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  playerInfo: {
    alignItems: 'center',
    marginBottom: 6,
  },
  playerPoints: {
    fontSize: 11,
    color: '#FFD700',
    fontFamily: 'monospace',
    marginTop: 3,
    fontWeight: 'bold',
  },
  pointButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  pointButton: {
    backgroundColor: '#228B22',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 2,
    borderColor: '#006400',
    minWidth: 40,
    alignItems: 'center',
  },
  threePointButton: {
    backgroundColor: '#8B0000',
    borderColor: '#5C0000',
  },
  pointButtonText: {
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  buttonsContainer: {
    marginTop: 30,
    alignItems: 'center',
    gap: 15,
  },
  finishButton: {
    backgroundColor: '#FFD700',
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderWidth: 4,
    borderColor: '#B8860B',
  },
  finishButtonDisabled: {
    backgroundColor: '#666666',
    borderColor: '#444444',
  },
  finishButtonText: {
    fontSize: 16,
    color: '#000000',
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
});