import { StyleSheet } from 'react-native';

export const teamSelectionStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  scrollContent: {
    alignItems: 'center',
    padding: 20,
    paddingBottom: 40,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#00FF00',
    textShadowColor: '#00AA00',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 0,
    marginTop: 20,
    marginBottom: 10,
    fontFamily: 'monospace',
  },
  subtitle: {
    fontSize: 18,
    color: '#FFD700',
    marginBottom: 30,
    fontFamily: 'monospace',
  },
  teamsContainer: {
    width: '100%',
    gap: 30,
  },
  teamSelector: {
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    padding: 20,
    borderWidth: 3,
    borderColor: '#00FF00',
    borderRadius: 0,
  },
  teamLabel: {
    fontSize: 20,
    color: '#FF00FF',
    fontWeight: 'bold',
    marginBottom: 15,
    fontFamily: 'monospace',
  },
  selectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 20,
    marginBottom: 15,
  },
  arrowButton: {
    backgroundColor: '#00FF00',
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#00AA00',
  },
  arrowText: {
    fontSize: 24,
    color: '#000000',
    fontWeight: 'bold',
  },
  teamName: {
    fontSize: 24,
    color: '#FFFFFF',
    fontWeight: 'bold',
    marginBottom: 15,
    fontFamily: 'monospace',
  },
  playersContainer: {
    width: '100%',
    backgroundColor: '#0a0a0a',
    padding: 15,
    borderWidth: 2,
    borderColor: '#FFD700',
  },
  playersTitle: {
    fontSize: 14,
    color: '#00FFFF',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'monospace',
  },
  playerName: {
    fontSize: 14,
    color: '#FFFFFF',
    marginVertical: 3,
    fontFamily: 'monospace',
  },
  playButton: {
    backgroundColor: '#FF0000',
    paddingHorizontal: 50,
    paddingVertical: 20,
    marginTop: 30,
    borderWidth: 4,
    borderColor: '#AA0000',
  },
  playButtonText: {
    fontSize: 24,
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  footer: {
    fontSize: 16,
    color: '#00FF00',
    marginTop: 20,
    fontFamily: 'monospace',
    opacity: 0.7,
  },
});