import { StyleSheet } from 'react-native';

export const gameOverStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#080810',
  },
  scrollContent: {
    alignItems: 'center',
    padding: 20,
    paddingTop: 40,
    paddingBottom: 40,
  },
  title: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#FFD700',
    fontFamily: 'monospace',
    letterSpacing: 3,
    textShadowColor: '#FFD700',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
    marginTop: 10,
    marginBottom: 16,
  },
  winnerContainer: {
    alignItems: 'center',
    marginBottom: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#FFD700',
    backgroundColor: '#0f0f20',
    width: '100%',
    borderRadius: 4,
  },
  winnerLabel: {
    fontSize: 18,
    color: '#00FF88',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    letterSpacing: 5,
    marginBottom: 12,
    textShadowColor: '#00FF88',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  winnerName: {
    fontSize: 22,
    color: '#F0F0FF',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    letterSpacing: 2,
    marginTop: 12,
  },
  finalScoreContainer: {
    alignItems: 'center',
    marginVertical: 10,
    padding: 10,
    backgroundColor: '#0f0f20',
    borderWidth: 1,
    borderColor: '#00EEFF',
    width: '100%',
    borderRadius: 4,
  },
  finalScoreLabel: {
    fontSize: 12,
    color: '#00EEFF',
    fontFamily: 'monospace',
    letterSpacing: 2,
    marginBottom: 6,
    textShadowColor: '#00EEFF',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  teamScoreName: {
    fontSize: 12,
    color: '#F0F0FF',
    fontFamily: 'monospace',
    letterSpacing: 1,
    width: 70,
    textAlign: 'center',
  },
  finalScore: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#F0F0FF',
    fontFamily: 'monospace',
    letterSpacing: 2,
    textShadowColor: '#FFD700',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  top5Container: {
    width: '100%',
    backgroundColor: '#0f0f20',
    padding: 10,
    borderWidth: 1,
    borderColor: '#FF10F0',
    marginVertical: 10,
    borderRadius: 4,
  },
  top5Title: {
    fontSize: 13,
    color: '#FF10F0',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    textAlign: 'center',
    letterSpacing: 3,
    marginBottom: 8,
    textShadowColor: '#FF10F0',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  top5Row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#1a1a2e',
  },
  top5Position: {
    fontSize: 12,
    color: '#FFD700',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    width: 24,
    textShadowColor: '#FFD700',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  top5PlayerInfo: {
    flex: 1,
    flexDirection: 'column',
  },
  top5PlayerName: {
    fontSize: 12,
    color: '#00EEFF',
    fontFamily: 'monospace',
    letterSpacing: 1,
  },
  top5TeamName: {
    fontSize: 10,
    color: '#444466',
    fontFamily: 'monospace',
  },
  top5Points: {
    fontSize: 12,
    color: '#00FF88',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    textShadowColor: '#00FF88',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  newGameButton: {
    backgroundColor: '#00FF88',
    paddingHorizontal: 40,
    paddingVertical: 14,
    borderWidth: 2,
    borderColor: '#00AA55',
    borderRadius: 4,
    marginTop: 10,
  },
  newGameButtonText: {
    fontSize: 18,
    color: '#080810',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    letterSpacing: 3,
  },
  footer: {
    fontSize: 14,
    color: '#1a1a2e',
    marginTop: 20,
    fontFamily: 'monospace',
  },
});
