import { StyleSheet } from 'react-native';

export const teamSelectionStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#080810',
    paddingTop: 40,
  },

  // 1. Header
  header: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f0f20',
    borderBottomWidth: 1,
    borderBottomColor: '#00FF88',
  },
  title: {
    fontSize: 34,
    fontWeight: 'bold',
    color: '#00FF88',
    fontFamily: 'monospace',
    letterSpacing: 3,
    textShadowColor: '#00FF88',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 15,
    color: '#00FF88',
    fontFamily: 'monospace',
    letterSpacing: 3,
    textShadowColor: '#00FF88',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },

  // 2 & 4. Selector de equipo
  teamBlock: {
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f0f20',
    borderBottomWidth: 1,
    borderBottomColor: '#1a1a2e',
    paddingVertical: 8,
  },
  teamLabel: {
    fontSize: 16,
    color: '#FF10F0',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    letterSpacing: 5,
    marginBottom: 12,
    textShadowColor: '#FF10F0',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  selectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 20,
    width: '100%',
    paddingHorizontal: 24,
  },
  arrowButton: {
    backgroundColor: '#00FF88',
    width: 65,
    height: 65,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#00AA55',
    borderRadius: 4,
  },
  arrowText: {
    fontSize: 30,
    color: '#080810',
    fontWeight: 'bold',
  },
  selectorCenter: {
    flex: 1,
    alignItems: 'center',
  },
  teamName: {
    fontSize: 20,
    color: '#F0F0FF',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    textAlign: 'center',
    letterSpacing: 2,
    marginTop: 9,
  },

  // 3 & 5. Quinteto
  playersBlock: {
    backgroundColor: '#0a0a1a',
    borderWidth: 1,
    borderColor: '#FFD700',
    alignSelf: 'center',
    marginVertical: 3,
    paddingHorizontal: 20,
    paddingVertical: 5,
    borderRadius: 3,
  },
  playersTitle: {
    fontSize: 12,
    color: '#00EEFF',
    fontFamily: 'monospace',
    textAlign: 'center',
    letterSpacing: 2,
    marginBottom: 3,
    textShadowColor: '#00EEFF',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  playerName: {
    fontSize: 14,
    color: '#F0F0FF',
    fontFamily: 'monospace',
    letterSpacing: 1,
    marginVertical: 1,
  },

  // 6. Botón jugar
  footer: {
    flex: 1.2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f0f20',
    borderTopWidth: 1,
    borderTopColor: '#00FF88',
  },
  playButton: {
    backgroundColor: '#FF2244',
    paddingHorizontal: 48,
    paddingVertical: 14,
    borderWidth: 2,
    borderColor: '#FF2244',
    borderRadius: 4,
  },
  playButtonText: {
    fontSize: 22,
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    letterSpacing: 4,
    textShadowColor: '#FF0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
});
